### ISSUE TITLE
Not working since 2016 May 14

### ISSUE THREAD

**Issue by alexgv99** [niqdev/packtpub-crawler#3] opened 2016-05-31 14:14 UTC
I just cloned, correct the prod.cfg with my data and try to run... if fails like the lines below.

[Tue 31/May 10:52] alexgv@PROC-PE0ZW ~/workspace/packtpub-crawler $ python script/spider.py --config config/prod.cfg

         __             __         __           __           __    __        __
        /\ \     __    /\ \       /\ \         /\ \         /\ \  /\ \    _ / /\
       /  \ \   /\_\   \ \ \     /  \ \       /  \ \____   /  \ \ \ \ \  /_/ / /
      / /\ \ \_/ / /   /\ \_\   / /\ \ \     / /\ \_____\ / /\ \ \ \ \ \ \___\/
     / / /\ \___/ /   / /\/_/  / / /\ \ \   / / /\/___  // / /\ \_\/ / /  \ \ \
    / / /  \/____/   / / /    / / /  \ \_\ / / /   / / // /_/_ \/_/\ \ \   \_\ \
   / / /    / / /   / / /    / / / _ / / // / /   / / // /____/\    \ \ \  / / /
  / / /    / / /   / / /    / / / /\ \/ // / /   / / // /\____\/     \ \ \/ / /
 / / /    / / /___/ / /__  / / /__\ \ \/ \ \ \__/ / // / /______      \ \ \/ /
/ / /    / / //\__\/_/___\/ / /____\ \ \  \ \___\/ // / /_______\      \ \  /
\/_/     \/_/ \/_________/\/________\_\/   \/_____/ \/__________/       \_\/

Download FREE eBook every day from www.packtpub.com
@see github.com/niqdev/packtpub-crawler
        
[+] configuration file: config/prod.cfg
[-] <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='www.packtpub.com', port=443): Max retries exceeded with url: /packt/offers/free-learning (Caused by <class 'httplib.BadStatusLine'>: '') | spider.py@41
Traceback (most recent call last):
  File "script/spider.py", line 41, in main
    packpub.run()
  File "/home/alexgv/workspace/packtpub-crawler/script/packtpub.py", line 110, in run
    self.__GET_login()
  File "/home/alexgv/workspace/packtpub-crawler/script/packtpub.py", line 46, in __GET_login
    response = self.__session.get(url, headers=self.__headers)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
ConnectionError: HTTPSConnectionPool(host='www.packtpub.com', port=443): Max retries exceeded with url: /packt/offers/free-learning (Caused by <class 'httplib.BadStatusLine'>: '')
[-] something weird occurred, exiting...
[Tue 31/May 10:52] alexgv@PROC-PE0ZW ~/workspace/packtpub-crawler $

**Comment by niqdev** [comment] 2016-05-31 17:01
Hi,
This error `Max retries exceeded` looks like a network error.
something in your network is changed? a proxy or a firewall? do you have a static ip?

**Comment by alexgv99** [comment] 2016-06-01 22:00
It seams ok... here a curl connecting to the proper url:

[Tue 31/May 10:52] alexgv@PROC-PE0ZW ~/workspace/packtpub-crawler $ curl -# -v https://www.packtpub.com/packt/offers/free-learning > output.txt
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 3128 (#0)
* Establish HTTP proxy tunnel to www.packtpub.com:443
> CONNECT www.packtpub.com:443 HTTP/1.1
> Host: www.packtpub.com:443
> User-Agent: curl/7.35.0
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.0 200 Connection established
< Connection: close
< 
* Proxy replied OK to CONNECT request
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: OU=GT23863044; OU=See www.rapidssl.com/resources/cps (c)15; OU=Domain Control Validated - RapidSSL(R); CN=*.packtpub.com
* 	 start date: 2015-03-30 03:23:14 GMT
* 	 expire date: 2018-07-01 00:37:31 GMT
* 	 subjectAltName: www.packtpub.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> GET /packt/offers/free-learning HTTP/1.1
> User-Agent: curl/7.35.0
> Host: www.packtpub.com
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server nginx/1.4.5 is not blacklisted
< Server: nginx/1.4.5
< Date: Wed, 01 Jun 2016 21:58:25 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Expires: Sun, 19 Nov 1978 05:00:00 GMT
< Cache-Control: public, s-maxage=172800
< Age: 30153
< Via: 1.1 varnish
< X-Country-Code: BR
< 
{ [data not shown]
######################################################################## 100,0%* Connection #0 to host 127.0.0.1 left intact

Attached the page downloaded correctly.
[output.txt](https://github.com/niqdev/packtpub-crawler/files/294438/output.txt)

**Comment by niqdev** [comment] 2016-06-02 09:06
:disappointed_relieved: I've just verified and everything works fine for me, maybe this is due to a libraries that you upgraded?
I have also upgraded my `requests` version from 2.7.0 to 2.10.0 and still work.

Do you have the possibility to run the script in another environment/machine just to understand if is only your problem or not? If I can't reproduce the error I don't know how to help you, sorry.
If you have any idea or you need that I verify some library versions or other things, just ask me.

**Comment by niqdev** [comment] 2016-06-09 18:23
Hi @alexgv99, do you still have the problem? Can I help you somehow? Otherwise I will close the issue.
Thanks

**Comment by alexgv99** [comment] 2016-06-10 04:07
Yes, I do have the same problem yet, but as I can't test anywhere else, I
mean, I tried at home, but in my house is Windows, not Linux, and I
couldn't configure the environment to run it... so I dropped... Go ahead
and close the thread... Thank you anyway for trying to help me.

Cordialmente.
Alex Gouvêa Vasconcelos
mailto:alexgv99@gmail.com
MSN: alexgv99@hotmail.com
http://about.me/alexgv99


2016-06-09 15:23 GMT-03:00 niqdev <notifications@github.com>:

**Comment by niqdev** [comment] 2016-06-10 06:33
If it can help you can have a look at [this](https://github.com/niqdev/packtpub-crawler/issues/2) on windows otherwise maybe wait for [this](https://github.com/niqdev/packtpub-crawler/issues/5).
Thanks

**Closed by niqdev** 2016-06-10 06:33 UTC
