### ISSUE TITLE
list index out of range | spider.py@97

### ISSUE THREAD

**Issue by xzl2021** [niqdev/packtpub-crawler#82] opened 2017-10-11 14:48 UTC
I have some problems. Is it same with #63 or #47 ? 
```
[*] 2017-10-11 22:40 - fetching today's eBooks
[*] configuration file: /root/packtpub-crawler/config/prod.cfg
[*] getting daily free eBook
[*] fetching url... 200 | https://www.packtpub.com/packt/offers/free-learning
[*] fetching url... 200 | https://www.packtpub.com//packt/offers/free-learning?login=1
[-] <type 'exceptions.IndexError'> list index out of range | spider.py@97
Traceback (most recent call last):
  File "script/spider.py", line 97, in main
    packtpub.runDaily()
  File "/root/packtpub-crawler/script/packtpub.py", line 161, in runDaily
    self.__parseDailyBookInfo(soup)
  File "/root/packtpub-crawler/script/packtpub.py", line 93, in __parseDailyBookInfo
    self.info['url_claim'] = self.__url_base + div_target.select('a.twelve-days-claim')[0]['href']
IndexError: list index out of range
[*] no free eBook from newsletter right now
[*] done

```

**Comment by niqdev** [comment] 2017-10-11 19:09
Thanks, is a duplicate of #70

**Closed as completed by niqdev** 2017-10-11 19:09 UTC
Labels: duplicate
