### ISSUE TITLE
"IndexError: list index out of range" while fetching newsletter

### ISSUE THREAD

**Issue by oujesky** [niqdev/packtpub-crawler#63] opened 2017-04-02 12:36 UTC
Since this week's newsletter, it started to throw the following exception. My guess is, that the structure of the landing page changed somewhat. 

```
[*] fetching url... 200 | https://www.packtpub.com/packt/free-ebook/what-you-need-know-about-angular-2
[-] <type 'exceptions.IndexError'> list index out of range | spider.py@125
Traceback (most recent call last):
  File "script/spider.py", line 125, in main
    packtpub.runNewsletter(currentNewsletterUrl)
  File "/home/mira/packtpub-crawler/script/packtpub.py", line 169, in runNewsletter
    self.__parseNewsletterBookInfo(soup)
  File "/home/mira/packtpub-crawler/script/packtpub.py", line 101, in __parseNewsletterBookInfo
    urlWithTitle = div_target.select('div.promo-landing-book-picture a')[0]['href']
IndexError: list index out of range
```

**Comment by juzim** [comment] 2017-04-02 13:28
Duplicate of https://github.com/niqdev/packtpub-crawler/issues/47

>

**Comment by niqdev** [comment] 2017-04-02 13:57
Thanks, yep the page is different

**Closed by niqdev** 2017-04-02 13:57 UTC
Labels: duplicate
